### ISSUE TITLE
root@169.254.8.1's password when flashing

### ISSUE THREAD

**Issue by pa2ngehe** [andymcca/sshflash-win#7]
i facing "root@169.254.8.1's password :" when flashing my leapster explorer, and no button on keyboard can be press except the enter key.
first attempt was "'ssh' is not recognized as an internal or external command, operable program or batch file." popped, using sshflash-win from  @andymcca

Then i used OpenSSH from @bagajjal [https://github.com/PowerShell/Win32-OpenSSH], and put the required files to do SSH, in the folder sshflash-win.v0,2,alpha that @andymcca forked, but all i got when in state start to flashing is 

> root@169.254.8.1's password :

am i did something wrong? i try to WinSCP and submit id.rsa key to that protocol, somehow i can log into those leapster explorer's folder.

I realy new into linux environment (just did a couple time on Retropie, Batocera.linux on OrangePiPC).

**Comment by andymcca** [comment]
I think I already spoke with you about this and got it resolved on another thread, but for anyone else who sees this -

You need to use OpenSSH 8.1 - newer versions don't support the RSA key that both sshflash and sshflash-win use to connect.  mac2612 has advised he will look to fix this in the next version of Retroleap.

**Comment by pa2ngehe** [comment]
yup...it's on mac's leapster fork.
And i should close this issue.
Thank's.
